apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      # Init container to create the folder
      initContainers:
        - name: init-folder
          image: busybox
          command: ['sh', '-c', '[ ! -d "/data/my-folder" ] && mkdir -p /data/my-folder || echo "Folder already exists"']
          volumeMounts:
            - name: my-data
              mountPath: /data
      # Main application container
      containers:
        - name: main-app
          image: nginx  # Replace with your application image
          volumeMounts:
            - name: my-data
              mountPath: /data
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: my-data-pvc


0---


# dev9.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: folder-config
data:
  FOLDER1: "data1"
  FOLDER2: "logs"
  FOLDER3: "config"
---
# deployment.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      initContainers:
        - name: create-folders
          image: busybox
          command: 
            - sh
            - -c
            - |
              for dir in "${FOLDER1}" "${FOLDER2}" "${FOLDER3}"; do
                if [ ! -d "/data/$dir" ]; then
                  echo "Creating $dir"
                  mkdir -p "/data/$dir"
                else
                  echo "Folder $dir already exists"
                fi
              done
          envFrom:
            - configMapRef:
                name: folder-config
          volumeMounts:
            - name: my-data
              mountPath: /data
      containers:
        - name: main-app
          image: nginx
          volumeMounts:
            - name: my-data
              mountPath: /data
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: my-data-pvc
